// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZpPs2KQk0rKY3rjA2vT6t7wpfaa06uVU',
    appId: '1:588780253868:web:35ff724367cef7a0076509',
    messagingSenderId: '588780253868',
    projectId: 'auten2',
    authDomain: 'auten2.firebaseapp.com',
    storageBucket: 'auten2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK66MOnY3xCUfYAsnXQV7W_9HZ1fN5Ks8',
    appId: '1:588780253868:android:3c95b1674c9229ad076509',
    messagingSenderId: '588780253868',
    projectId: 'auten2',
    storageBucket: 'auten2.appspot.com',
  );

  //  static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey:,
  //   appId:'1:588780253868:android:3c95b1674c9229ad076509',
  //   projectId: 'auten2',
  //   storageBucket: 'auten2.appspot.com',
  // );
}

 